# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foursquare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_search',
            name='search_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='search_date'),
        ),
    ]
