# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquare', '0002_auto_20171010_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_search',
            old_name='location_text',
            new_name='hehe',
        ),
    ]
