# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foursquare', '0003_auto_20171010_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location_search',
            name='food_text',
        ),
        migrations.RemoveField(
            model_name='location_search',
            name='hehe',
        ),
        migrations.AddField(
            model_name='location_search',
            name='food',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location_search',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
