# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquare', '0004_auto_20171010_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location_search',
            new_name='LocationSearch',
        ),
    ]
