# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foursquare', '0005_auto_20171011_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsearch',
            name='food',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='locationsearch',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
