# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursquare', '0010_auto_20171025_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
