# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foursquare', '0013_auto_20171025_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsearch',
            name='searched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
