# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foursquare', '0014_locationsearch_searched_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='foursquare/static/images/'),
        ),
    ]
