# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foursquare', '0015_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/default-avatar.png', upload_to='static/images/'),
        ),
    ]
