# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foursquare', '0016_auto_20171026_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/default-avatar.png', upload_to='images/'),
        ),
    ]
