# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foursquare', '0017_auto_20171030_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsearch',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
